### ISSUE TITLE
Android 64 Bits Support?

### ISSUE THREAD

**Issue by varelaj** [iBicha/EmojiTexture#26]
Hello, I just realized when compiling for Android 64 bits, it crashes.

**Comment by gromilQaaaa** [comment]
This zip contains repacked aar. Replace it in Plugins/Android subfolder
[emojitexture-debug.aar.zip](https://github.com/iBicha/EmojiTexture/files/5546277/emojitexture-debug.aar.zip)

**Comment by varelaj** [comment]
Thanks!

**Comment by raphaelns-developer** [comment]
For me a 64 bits using il2cpp it's not working:
```
Exception: /Applications/Unity/Hub/Editor/2019.4.35f1/Unity.app/Contents/il2cpp/build/deploy/il2cppcore/il2cppcore.dll did not run properly!

Failed running "/Applications/Unity/Hub/Editor/2019.4.35f1/Unity.app/Contents/il2cpp/build/deploy/il2cppcore/il2cppcore.dll" --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARM64" --configuration="Release" --outputpath="/Users/rsantos/TestEmoji/Temp/StagingArea/assets/bin/Data/Native/arm64-v8a/libil2cpp.so" --cachedirectory="/Users/rsantos/TestEmoji/Assets/../Library/il2cpp_android_arm64-v8a/il2cpp_cache" --additional-include-directories="/Applications/Unity/Hub/Editor/2019.4.35f1/PlaybackEngines/AndroidPlayer/Tools/bdwgc/include" --additional-include-directories="/Applications/Unity/Hub/Editor/2019.4.35f1/PlaybackEngines/AndroidPlayer/Tools/libil2cpp/include" --tool-chain-path="/Applications/Unity/Hub/Editor/2019.4.35f1/PlaybackEngines/AndroidPlayer/NDK" --profiler-report --map-file-parser="/Applications/Unity/Hub/Editor/2019.4.35f1/Unity.app/Contents/Tools/MapFileParser/MapFileParser" --directory="/Users/rsantos/TestEmoji/Temp/StagingArea/assets/bin/Data/Managed" --generatedcppdir="/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput"  

stdout:
Building libil2cpp.so with AndroidToolChain
	Output directory: /Users/rsantos/TestEmoji/Temp/StagingArea/assets/bin/Data/Native/arm64-v8a
	Cache directory: /Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache
ObjectFiles: 150 of which compiled: 0
Total compilation time: 71 milliseconds.
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: /Applications/Unity/Hub/Editor/2019.4.35f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ @"/var/folders/rj/yhxvrj1x6p1d9pzz00cl_fsh0000gp/T/tmpH5BPIa.tmp" -o "/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/linkresult_E715329E836321EFE45288BBE226422E/libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target aarch64-linux-android21 -Wl,--wrap,sigaction -llog -rdynamic -fuse-ld=bfd

/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `WebGLEmojiProvider_EmojiTexture_render_m23BDEC99642AD05F19843AB6312058E27D31C16B':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26571: undefined reference to `EmojiTexture_render'
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26571: undefined reference to `EmojiTexture_render'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_render_m901C229C8BEE68B770E1C710C42CE9CB405F29B9':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26784: undefined reference to `EmojiTexture_render'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_GetTextureUpdateCallback_mC9F820BA96D6A445E3E8B35791F9B866AAA094F1':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26799: undefined reference to `EmojiTexture_GetTextureUpdateCallback'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_SetBufferRefByIndexFunction_m6F67CA82949B92B3A75390CC3CC21D9B96D15347':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26814: undefined reference to `EmojiTexture_SetBufferRefByIndexFunction'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_GetTextureUpdateCallback_mC9F820BA96D6A445E3E8B35791F9B866AAA094F1':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26799: undefined reference to `EmojiTexture_GetTextureUpdateCallback'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_SetBufferRefByIndexFunction_m6F67CA82949B92B3A75390CC3CC21D9B96D15347':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26814: undefined reference to `EmojiTexture_SetBufferRefByIndexFunction'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_render_m901C229C8BEE68B770E1C710C42CE9CB405F29B9':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26784: undefined reference to `EmojiTexture_render'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)


   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args, List`1 foundAssemblies)
   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: /Applications/Unity/Hub/Editor/2019.4.35f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ @"/var/folders/rj/yhxvrj1x6p1d9pzz00cl_fsh0000gp/T/tmpH5BPIa.tmp" -o "/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/linkresult_E715329E836321EFE45288BBE226422E/libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target aarch64-linux-android21 -Wl,--wrap,sigaction -llog -rdynamic -fuse-ld=bfd

/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `WebGLEmojiProvider_EmojiTexture_render_m23BDEC99642AD05F19843AB6312058E27D31C16B':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26571: undefined reference to `EmojiTexture_render'
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26571: undefined reference to `EmojiTexture_render'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_render_m901C229C8BEE68B770E1C710C42CE9CB405F29B9':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26784: undefined reference to `EmojiTexture_render'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_GetTextureUpdateCallback_mC9F820BA96D6A445E3E8B35791F9B866AAA094F1':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26799: undefined reference to `EmojiTexture_GetTextureUpdateCallback'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_SetBufferRefByIndexFunction_m6F67CA82949B92B3A75390CC3CC21D9B96D15347':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26814: undefined reference to `EmojiTexture_SetBufferRefByIndexFunction'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_GetTextureUpdateCallback_mC9F820BA96D6A445E3E8B35791F9B866AAA094F1':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26799: undefined reference to `EmojiTexture_GetTextureUpdateCallback'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_SetBufferRefByIndexFunction_m6F67CA82949B92B3A75390CC3CC21D9B96D15347':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26814: undefined reference to `EmojiTexture_SetBufferRefByIndexFunction'
/Users/rsantos/TestEmoji/Library/il2cpp_android_arm64-v8a/il2cpp_cache/FBA865C933B1BFF886A8EE99BD6226B1.o: In function `iOSEmojiProvider_EmojiTexture_render_m901C229C8BEE68B770E1C710C42CE9CB405F29B9':
/Users/rsantos/TestEmoji/Temp/StagingArea/Il2Cpp/il2cppOutput/EmojiTexture.cpp:26784: undefined reference to `EmojiTexture_render'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)


   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args, List`1 foundAssemblies)
   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture)
   at il2cpp.Program.Main(String[] args)
   at Program.Main(String[] args) in /Users/bokken/buildslave/unity/build/External/il2cpp/il2cpp/il2cppcore/Program.cs:line 24

UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:126)
UnityEditorInternal.Runner.RunNetCoreProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:77)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:718)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data, System.String outputDirectory, System.String workingDirectory, System.Boolean platformSupportsManagedDebugging) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:701)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:538)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:266)
UnityEditor.Android.PostProcessor.Tasks.RunIl2Cpp.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <7f332f12abb94c1bb4cc658c3c10e91f>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <7f332f12abb94c1bb4cc658c3c10e91f>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <7f332f12abb94c1bb4cc658c3c10e91f>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <7f332f12abb94c1bb4cc658c3c10e91f>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:353)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)
```
